GET http://localhost:5000/api/prompts

###

GET http://localhost:5000/api/prompts/1

###
POST  http://localhost:5000/api/prompts
Content-Type: application/json

{
    "Question": "Apa ibukota Indonesia2?",
    "Answer":"Jakarta"
}
###
GET  http://localhost:5000/api/prompts
Content-Type: application/json

{
    "Question": "Apa ibukota Indonesia2?",
    "Answer":"Jakarta"
}

###
PATCH   http://localhost:5000/api/prompts/1
Content-Type: application/json

{
    "Question": "Apa ibukota Indonesia?",
    "Answer":"Jakarta"
}

###
DELETE   http://localhost:5000/api/prompts/1

###
POST  http://localhost:5000/api/histories
Content-Type: application/json

{
    "ChatId" : 2,
    "BubbleId" : 1,
    "Text": "Halo3",
    "Sender":"user"
}

###

GET http://localhost:5000/api/histories

###

GET http://localhost:5000/api/histories/1