GET http://localhost:5000/api/prompts

###

GET http://localhost:5000/api/prompts/1

###
POST  http://localhost:5000/api/prompts
Content-Type: application/json

{
    "Question": "Apa ibukota Indonesia2?",
    "Answer":"Jakarta"
}

###
PATCH   http://localhost:5000/api/prompts/1
Content-Type: application/json

{
    "Question": "Apa ibukota Indonesia?",
    "Answer":"Jakarta"
}

###
DELETE   http://localhost:5000/api/prompts/1
