GET http://localhost:5000/prompts

###

GET http://localhost:5000/prompts/5

###
POST  http://localhost:5000/prompts
Content-Type: application/json

{
    "question": "Apa ibukota Thailand?",
    "answer":"Bangkok"
}

###

PATCH  http://localhost:5000/prompts/1
Content-Type: application/json

{
    "question": "Apa ibukota Malaysia?",
    "answer":"Kuala Lumpur"
}

###
DELETE   http://localhost:5000/prompts/4
